function repo_help
    echo "Usage: repo <command> <repository>"
    echo ""
    echo "Commands:"
    echo "  get        Clone a repository to the repos directory"
    echo "  open       Open the current repository in the browser"
    echo "  aur        Clone an AUR repository"
    echo "  list       List all repositories"
    echo "  go|goto    Navigate to a repository"
    echo "  new|create Create a new repository"
    echo "  help       Show this help message"
    echo ""
    echo "Examples:"
    echo "  repo get github.com/user/repo"
    echo "  repo open"
end